services:
  redis:
    image: redis:7.0-alpine
    container_name: alpine-redis
    ports:
      - 6379:6379

  api:
    image: ankitpwr/diagnose-api
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: diagnose-api
    ports:
      - 3000:3000
    env_file:
      - ./server/.env
    depends_on:
      - redis
